app/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webbook.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # 회원가입
    path('register/', views.Registration.as_view(), name='register'),
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    # 로그아웃
    path('logout/', views.Logout.as_view(), name='logout'),
]

webbook/urls.py
from django.urls import path
from . import views


app_name='webbook'

urlpatterns = [
    path('', views.Index.as_view(), name='list'),
    # 글 상세 조회
    path("detail/<int:pk>/ ", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 책 리스트
    path('novel_list', views.novel_list, name='novel_list'),
    # 책 상세
    path('novel/<int:novel_id>/', views.novel_detail, name='novel_detail'),
    # 챕터 상세
    path('novel/<int:novel_id>/chapter/<int:chapter_number>/', views.chapter_detail, name='chapter_detail'),
    # 책 작성
    path('create_novel/', views.create_novel, name='create_novel'),
    # 책 수정
    path('update_novel/<int:novel_id>/', views.update_novel, name='update_novel'),
    # 책 삭제
    path('delete_novel/<int:novel_id>/', views.delete_novel, name='delete_novel'),
    # 챕터 생성
    path('novel/<int:novel_id>/create_chapter/', views.create_chapter, name='create_chapter'),
    # 챕터 수정
    path('novel/<int:novel_id>/update_chapter/<int:chapter_number>/', views.update_chapter, name='update_chapter'),
    path('novel/<int:novel_id>/delete_chapter/<int:chapter_number>/', views.delete_chapter, name='delete_chapter'),
]

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="/static/javascript/javascript.js"></script>
    <title>
      {% block title %}
        {{ title }}
      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container">
      <h2>webbook</h2>
    <button type="button" class="collapsible" onclick="collapse(this);">메뉴</button>
    <div class="content">
        <p><a href="{% url 'user:register' %}">회원가입</a></p>
        <p><a href="{% url 'user:login' %}">로그인</a></p>
        <p><a href="{% url 'webbook:list' %}">게시판 리스트</a></p>
        <p><a href="{% url 'webbook:write' %}">게시판 작성</a></p>
        <p><a href="{% url 'webbook:novel_list' %}">소설 목록</a></p>
        <p><a href="{% url 'webbook:create_novel' %}">글쓰기</a></p>
    </div>
    <div class="container">
      {% if user.is_authenticated %}
        <p>
          {% trans 'Welcome,' %} {{ user.email }}
        </p>
        <a href="{% url 'user:logout' %}" class="btn">Logout</a>
      {% else %}
        <p>
          {% trans 'Please, Login' %}
        </p>
        <a href="{% url 'user:login' %}" class="btn">Login</a>
      {% endif %}

      <h1><a href="{% url 'webbook:list' %}">Blog</a></h1>

      {% block content %}

      {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>